config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'app#index'

  #post '/projects', to: 'projects#create'
  resources :projects do
  	resources :tasks 
  end

  get '/projects/new', to: 'projects#new'

  get '/login', to: 'sessions#new'
  post '/logout', to: 'sessions#destroy' #get?
  get '/register', to: 'users#new'

  post '/users', to: 'users#create'
  post '/sessions', to: 'sessions#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to :user
	has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  validates :login, uniqueness: { case_sensitive: false }
	has_many :projects, dependent: :destroy
	has_secure_password
end

app/controllers/app_controller.rb
class AppController < ApplicationController

	def index
		if @current_user
		  @projects = Project.where(user_id: @current_user.id)
		end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :get_current_user

  private
    def get_current_user
    	if session[:user_id]
    		@current_user = User.find_by_id(session[:user_id])
        if @current_user.nil? #fallback for when cookie is present but user is deleted
          session[:user_id] = nil 
        end
    	end
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authorize, only: [:destroy, :update] #create?

  def new
    respond_to do |f|
      f.js 
    end
  end

	def create
		@project = Project.create(name: params[:name], user_id: @current_user.id)
		
    respond_to do |f|
      f.js 
    end
	end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    respond_to do |f|
      f.js 
    end 
  end 

  def update
    @project = Project.find(params[:id])
    if params[:edit]
      render 'edit.js.erb'
    end
    if params[:name]
      @project.update(name: params[:name])
      render 'show.js.erb'
    end
  end

  private
    def authorize
      if @current_user.id != Project.find(params[:id]).user_id
        redirecto_to '/login'
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new	
	end

	def create
		user = User.find_by(login: params[:login])
		if user 
			@user = user.authenticate(params[:password])
			if @user
				session[:user_id] = @user.id
				redirect_to '/'
			else #TODO: DRY
				flash[:alert] = "Wrong user or password"
				redirect_to '/login'
			end
		else
			flash[:alert] = "Wrong user or password"
			redirect_to '/login'
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to '/'
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authorize, only: [:destroy, :update]

	def create
		@project = Project.find(params[:project_id])
		@task = @project.tasks.create(text: params[:text], status: false)

    respond_to do |format|
      format.js
    end
	end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.js
    end
  end

  def update
    @task = Task.find(params[:id])
    if params[:status]
      @task.update(status: params[:status])
      render 'status.js.erb'
    elsif params[:edit]
      render 'edit.js.erb'
    elsif params[:text]
      @task.update(text: params[:text])
      render 'show.js.erb'
    end
    respond_to do |format|
      format.js
    end
  end

  private
    def authorize
      if Task.find(params[:id]).project.user.id != @current_user.id
        redirect_to '/login'
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
	end

	def create
		if @user = User.create(login: params[:login], 
			                  password: params[:password])
                    .valid?
      flash[:success] = 'User created'
    else
      flash[:error] = 'Login already exists'
    end
    redirect_to '/'
	end
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/app/index.html.erb
<header class="app__header">
	<h1>SIMPLE TODO LISTS</h1>
	<h2>FROM RUBY GARAGE</h2>
</header>
<% flash.each do |type, mes| %>
  <p>
  	<span><%= type %>:</span>
  	<span><%= mes %></span>
  </p>
<% end %>
<% if !@current_user %>
	<div class="app__not-logged-in">
		<h2><a href="/login">Log in</a></h2>
  	<h2><a href="/register">Register</a></h2>
	</div>
<% else %>
	<div class="app__logout">
		<span class="logout__user-icon">&#x26C4;</span>
		<span class="logout__username"><%= @current_user.login %></span>
		<span class="logout__button">
		  <%= button_to "Log out", logout_path %>
		</span>
	</div>
	<div class="app__projects">
		<% if @projects %>
	  	<%= render @projects %>
	  <% end %>
	</div>
	<div class="app__add-project">
	  <%= button_to "Add TODO List", new_project_path, method: :get, remote: true %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_edit.html.erb
<%= form_with url: project_path(@project.id), method: :patch, class: 'project-edit__form' do |f| %>
  <%= f.text_field :name, value: @project.name %>
  <%= f.submit "save" %>
<% end %>

app/views/projects/_header.html.erb
<div class="project__header">
  <div class="header__title">
    <%= project.name %>
  </div>
  <div class="header__controls">
    <div class="control__edit">
      <%= button_to "", project_path(project.id), method: :patch, remote: true, params: { edit: true } %>
    </div>
    <div class="control__delete">
      <%= button_to "", project_path(project.id), method: :delete, remote: true %>
    </div>
  </div>
</div>

app/views/projects/_new.html.erb
<%= form_with url: projects_path, class: 'add-project__form' do |f| %>
  <%= f.text_field :name %>
  <%= f.submit 'Add project' %>
<% end %>

app/views/projects/_project.html.erb
<div class="project" data-project-id="<%=project.id%>">
  <%= render partial: '/projects/header', locals: {project: project } %>
  <div class="project__task-form">
    <%= form_with url: project_tasks_path(project.id) do |f| %>
      <%= f.text_field :text, class: "task-form__text", placeholder: "Start typing here to create a task..." %>
      <%= f.submit "Add Task", class: "task-form__submit" %>
    <% end %>
  </div>
  <div class="project__tasks">
    <%= render project.tasks %>
  </div>
</div>

app/views/projects/create.js.erb
var el = document.createElement('div');
el.innerHTML = '<%= j render @project %>';

qs('.app__projects').appendChild(el);

qs('.app__add-project').innerHTML = 
'<%= j button_to "Add TODO List", new_project_path, method: :get, remote: true %>';

app/views/projects/destroy.js.erb
var el = qs('[data-project-id=\"<%= @project.id %>\"]');
el.remove();

app/views/projects/edit.js.erb
var el = qs('.project[data-project-id=\"<%= @project.id %>\"] .project__header');
el.innerHTML = "<%= j render 'edit' %>";
el.querySelector('form input[name=\"name\"]').focus();

app/views/projects/new.js.erb
var form = '<%= j render "new" %>';
var el = document.querySelector('.app__add-project');
el.innerHTML = form;

app/views/projects/show.js.erb
var el = qs('.project[data-project-id=\"<%= @project.id %>\"] .project__header');
el.insertAdjacentHTML('afterend', '<%= j render partial: "header", locals: {project: @project } %>');
el.remove();

app/views/tasks/_edit.html.erb
<%= form_with url: project_task_path(@task.project.id, @task.id), method: :patch, class: 'task__edit' do |f| %>
  <%= f.text_field :text, value: @task.text %>
  <%= f.submit "save" %>
<% end %>

app/views/tasks/_task.html.erb
<% ptp = project_task_path(task.project.id, task.id) %>

<div class="task <%= task.status ? 'is_done' : '' %>" data-task-id="<%= task.id %>">
  <div class="task__done">
    <%= button_to "\u26AA", ptp, method: :patch, remote: true, params: { status: true } %>
  </div>
  <div class="task__text"><%= task.text %></div>
  <div class="task__controls">
    <div class="control__move">
      <%= button_to "", ptp, method: :patch, remote: true, disabled: true %>    
    </div>
    <div class="control__edit">
      <%= button_to "", ptp, method: :patch, remote: true, params: { edit: true } %>
    </div>
    <div class="control__delete">
      <%= button_to "", ptp, method: :delete, remote: true %>
    </div>
  </div>
</div>

app/views/tasks/create.js.erb
var parent = qs('.project[data-project-id=\"<%= @project.id %>\"] .project__tasks');
//var el = document.createElement('div');
//el.innerHTML = '<%= j render @task %>';
//parent.appendChild(el);
parent.insertAdjacentHTML('beforeend', '<%= j render @task %>');
var form = document.querySelector('.project[data-project-id=\"<%= @project.id %>\"] .project__task-form form input[type=text]');
form.value = '';

app/views/tasks/destroy.js.erb
qs('.task[data-task-id=\"<%= @task.id %>\"]').remove();

app/views/tasks/edit.js.erb
var el = qs('.task[data-task-id=\"<%= @task.id %>\"]');
el.innerHTML = "<%= j render 'edit', locals: {task: @task } %>";

app/views/tasks/show.js.erb
var el = qs('.task[data-task-id=\"<%= @task.id %>\"]');
el.insertAdjacentHTML('afterend', '<%= j render partial: "task", locals: {task: @task } %>');
el.remove();

app/views/tasks/status.js.erb
<% ptp = project_task_path(@task.project.id, @task.id) %>
var task = qs('.task[data-task-id=\"<%= @task.id %>\"]');
<% if @task.status %>
  task.classList.add('is_done');
  task.querySelector('.task__done').innerHTML = '<%= j button_to "\u26AA", ptp, method: :patch, remote: true, params: { status: false } %>';
<% else %>
  task.classList.remove('is_done');
  task.querySelector('.task__done').innerHTML = '<%= j button_to "\u26AA", ptp, method: :patch, remote: true, params: { status: true } %>';
<% end %>

app/views/users/new.html.erb
<header class="app__header">
  <h1>SIMPLE TODO LISTS</h1>
  <h2>FROM RUBY GARAGE</h2>
</header>
<% if flash[:alert] %>
  <%= flash[:alert] %>
<% end %>
<div class="app__log-in app__register">
  <h1>Register</h1>
  <%= form_with url: users_path do |f| %>
    <%= f.text_field :login, placeholder: 'Username' %></p>
    <%= f.password_field :password, placeholder: 'Password' %></p>
    <%= f.submit "register" %>
  <% end %>
</div>